name: Archive Stale Branches

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  archive_stale_branches:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get list of branches
        run: |
          echo "Getting list of branches..."
          BRANCHES=$(git branch --list "*" | grep -v "master")
          
      - name: Loop through branches
        run: |
          echo "Checking branches for stale status..."
          archive_count=0
          for branch in $BRANCHES
          do
            if [ "$branch" == "* master" ]; then
              continue
            fi

            if [ "$branch" == "$GITHUB_DEFAULT_BRANCH" ]; then
              continue
            fi
          
            if ! git log -1 --pretty=%d $branch | grep "HEAD -> $branch"; then
              echo "Branch $branch is stale. Archiving..."
              
              git tag archive/$branch-$(date +%Y-%m-%d) $branch
              git push origin --tags
              
              git push origin --delete $branch
              
              archive_count=$((archive_count + 1))
            fi
          done

      - name: Log results
        if: archive_count > 0
        run: |
          echo "Archived $archive_count branches"
          
      - name: Log no branches found
        if: archive_count == 0
        run: |
          echo "No branches found to be archived"
